using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PausaMenu : MonoBehaviour
{
    [SerializeField] private GameObject pauseMenuUI;
    [SerializeField] private bool isPaused;

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.P))
        {
            isPaused = !isPaused;
        }

        if (isPaused)
        {
            ActivarMenu();
        }

        else
        {
            DesactivarMenu();
        }
    }

      public void ActivarMenu()
        {
            pauseMenuUI.SetActive(true);
            Time.timeScale = 0;
            AudioListener.pause = true;
        }

        public void DesactivarMenu()
        {
            pauseMenuUI.SetActive(false);
            Time.timeScale = 1;
            AudioListener.pause = false;
            isPaused = false;
        }

    public void SalirJuego()
    {
        SceneManager.LoadScene("Menu");
    }
    
}
